[versions]
agp = "8.9.3"
kotlin = "2.2.21"
compose-multiplatform = "1.10.3"
activity-compose = "1.13.0"
coroutines = "1.11.0"
datetime = "0.8.0"
serialization = "1.11.0"
kermit = "2.1.0"
koin = "4.2.2"
compose-material-icons = "1.7.3"
androidsvg = "1.4"
batik = "1.19"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
composeMaterialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koinCompose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }
batikTranscoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batik" }
