[versions]
agp = "8.9.3"
kotlin = "2.2.0"
compose-multiplatform = "1.10.3"
activity-compose = "1.10.1"
coroutines = "1.10.2"
datetime = "0.7.1"
serialization = "1.9.0"
kermit = "2.1.0"
koin = "4.1.1"
compose-material-icons = "1.7.3"
androidsvg = "1.4"
batik = "1.17"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
composeFoundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
composeMaterialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
composeMaterial3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-multiplatform" }
composePreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
composeRuntime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
composeUi = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
composeUiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koinCompose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }
batikTranscoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batik" }
